### ISSUE TITLE
Getting Started with the MAX78000 Evaluation Kit 

### ISSUE THREAD

**Issue by joachimckh** [MaximIntegratedAI/MaximAI_Documentation#40]
Hi,

I've been trying to follow the guide in: https://github.com/MaximIntegratedAI/MaximAI_Documentation/blob/master/MAX78000_Evaluation_Kit/README.md

for the MAX78000FTHR, however, my microcontroller does not seem to produce the expected output. by following the steps 1-9 in Loading and Running Applications on the EV Kit. I'm trying the simplest "Hello World" example, but when I reach step 9. and press c in my console, the only output is "Continuing." while the controller blinks red. I've been resetting it several times, and even tried a new one without success. What exactly am I doing wrong?

Thanks in advance,
Joachim

**Comment by aniktash** [comment]
Hi, I tried the instructions and didn't see any issue. 
Only in step 6, the elf is in build folder, (arm-none-eabi-gdb build/max78000.elf).  You can exit the gdb and OpenOCD with CNTRL+C and see if it starts. If it flashed correctly as checked in step 8, the Green led should blink and it should print counts.
You can also flash in single step with OpenOCD without gdb:
Go to Hello_World directory, **make -r** to build and flash using:
**$ openocd -s C:/MaximSDK/Tools/OpenOCD/scripts -f interface/cmsis-dap.cfg -f target/max78000.cfg  -c "program build/MAX
78000.elf reset exit"**

**Comment by joachimckh** [comment]
It does indeed blink green, but no output is printed in console. The LED pear next to the camera, however, also blinks red which I assume is not intended, so something must be going wrong. This is the case for both my microcontrollers.

I tried to flash in a single step and get following output:

Open On-Chip Debugger 0.10.0+dev-gdb3807dd7-dirty (2020-11-06-09:24)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
DEPRECATED! use 'adapter driver' not 'interface'
Info : CMSIS-DAP: SWD  Supported
Info : CMSIS-DAP: FW Version = 0256
Info : CMSIS-DAP: Serial# = 04441701198fcc1b00000000000000000000000097969906
Info : CMSIS-DAP: Interface Initialised (SWD)
Info : SWCLK/TCK = 1 SWDIO/TMS = 1 TDI = 0 TDO = 0 nTRST = 0 nRESET = 1
Info : CMSIS-DAP: Interface ready
Info : clock speed 2000 kHz
Info : SWD DPIDR 0x2ba01477
Info : max32xxx.cpu: hardware has 6 breakpoints, 4 watchpoints
Info : starting gdb server for max32xxx.cpu on 3333
Info : Listening on port 3333 for gdb connections
Info : SWD DPIDR 0x2ba01477
target halted due to debug-request, current mode: Thread
xPSR: 0x81000000 pc: 0x00002120 msp: 0x20003ff0
** Programming Started **
Error: couldn't open build/MAX
embedded:startup.tcl:521: Error: ** Programming Failed **
in procedure 'program'
in procedure 'program_error' called at file "embedded:startup.tcl", line 586
at file "embedded:startup.tcl", line 521

**Comment by vicloginov** [comment]
You could not flash in single step probably because of extra space/LF after "build/MAX" in your command
**Error: couldn't open build/MAX**

**Comment by vicloginov** [comment]
Also, select correct COM port and set data rate to 115200 bps to see messages

**Comment by Sandlavish** [comment]
Hi, 
I am working on the keyword detection project using MAX78000 feather board. I have selected the correct COM port and set data rate to 115200 bps. The only output that I am getting is the classification result. What do I do next to display the keyword detection output? 
Note: I am using a Mac and therefore, can't use the sdk.

**Comment by joachimckh** [comment]
Hi @vicloginov, I finally managed it to work, thanks a lot for your inputs!

**Comment by aniktash** [comment]
Hi,
The kws20_v3 project is an auto generated Known Answer Test code that displays the classification result for the provided sampledata.
Please use the kws20_demo application which captures audio samples from mic and displays the detected words through COM port and optionally on the TFT display (please check the readme for more info on display)

Thanks
Afshin


From: Apoorv Tewari ***@***.***>
Sent: Friday, August 20, 2021 12:33 AM
To: MaximIntegratedAI/MaximAI_Documentation ***@***.***>
Cc: Afshin Niktash ***@***.***>; Assign ***@***.***>
Subject: [EXTERNAL] Re: [MaximIntegratedAI/MaximAI_Documentation] Getting Started with the MAX78000 Evaluation Kit (#40)

EXTERNAL EMAIL



Hi,
I am working on the keyword detection project using MAX78000 feather board. I have selected the correct COM port and set data rate to 115200 bps. The only output that I am getting is the classification result. What do I do next to display the keyword detection output?
Note: I am using a Mac and therefore, can't use the sdk.

-
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMaximIntegratedAI%2FMaximAI_Documentation%2Fissues%2F40%23issuecomment-902496122&data=04%7C01%7Cafshin.niktash%40maximintegrated.com%7Ce8f3b36e7a5c4884e84808d963acc750%7Cfbd909dfea694788a554f24b7854ad03%7C0%7C0%7C637650416003235636%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=F3hCguRP6gDMI3B%2BleH%2BP%2F4qVMabq2GGBgSyNf1hQFY%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALOPVCCKTXUCQOE2LJJMLXDT5YALRANCNFSM5CBBT7BA&data=04%7C01%7Cafshin.niktash%40maximintegrated.com%7Ce8f3b36e7a5c4884e84808d963acc750%7Cfbd909dfea694788a554f24b7854ad03%7C0%7C0%7C637650416003235636%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=lU6vXStzH%2BnpeoGC8MwOnC4MJNadN7wembyCIYpNDT0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cafshin.niktash%40maximintegrated.com%7Ce8f3b36e7a5c4884e84808d963acc750%7Cfbd909dfea694788a554f24b7854ad03%7C0%7C0%7C637650416003245628%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=PfRYVtFLcaKyuQQLXeZdfoPW24z57R6Yn7GsR2Wv69c%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cafshin.niktash%40maximintegrated.com%7Ce8f3b36e7a5c4884e84808d963acc750%7Cfbd909dfea694788a554f24b7854ad03%7C0%7C0%7C637650416003245628%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Zq%2FRorSvnL%2BgmvyOyc%2F9o3hQqqykOQG%2FHwgbqRT6FBQ%3D&reserved=0>.
