### ISSUE TITLE
How to input image or use predefined image and convert it to uint32_t?

### ISSUE THREAD

**Issue by srajanseth84** [MaximIntegratedAI/MaximAI_Documentation#47]
input image is predefined in this [example](https://github.com/MaximIntegratedAI/MAX78000_SDK/blob/master/Examples/MAX78000/CNN/mnist/sampledata.h)
I want to change that but I couldn't find any code that convert image to uint32_t or how to crop image and integrate with existing code
How to change predefined image or change that input array?
And how to perform operation on that array like Croping ?
Or Do i first need to crop then convert?

**Comment by Jake-Carter** [comment]
@srajanseth84 
> That means We can't convert jpeg or png to CHW index inside main.c.

On the micro core itself you are very rarely dealing with jpeg or png formats directly. 
 Usually you're dealing with the raw output of camera modules.  There's no real reason you _couldn't_ decode jpeg or pngs on the micro core, but the image data will always need to be passed into the FIFO in the CHW format... 

> So then I have to train, quantize all from starting to change that input image.

There is built-in support in the training tools for converting to CHW during training.  Check out the [dataset transforms](https://github.com/MaximIntegratedAI/ai8x-training/blob/67e263b3974213a72c25e29c7f678184d7fbac85/datasets/mnist.py#L55) in the mnist data loader.  These transforms convert from a PIL image format to CHW using PyTorch transforms, so the mnist model already is doing that. [This](https://www.maximintegrated.com/en/design/technical-documents/app-notes/7/7600.html) app note goes very deep into the data loader design.

But yes - you will _always_ need to train a model using the the same quantization.  This is just a reality of the hardware.

> Can I do something like
> 
> ```
> cnn_init(); 
> cnn_load_weights();
> cnn_load_bias();
> cnn_configure();
> load_input(); 
> for (int i=0;i<8;i++) // because I want 8 cropped digits from that image and then passon 
> {
> copy_(1,2,3,...8)_cropped_image_to_memory();
> cnn_start();
> then_pass_that_to_model_and_show_output
> //....
> }
> cnn_disable();
> return 0;
> ```

This will only work if your model has been designed to accept all 8 digit images at once.  This will not work with the pre-trained mnist model, since it's only designed to accept one digit at a time.  You would need something like ...

```
cnn_init(); 
cnn_load_weights();
cnn_load_bias();
cnn_configure();
for (int i=0;i<8;i++) { // For each digit
    load_input(); // This should contain your copy_(i)_cropped_image_to_memory(); function and load it into the FIFO
    cnn_start(); // This starts the CNN accelerator
    show_output
    //....
}
cnn_disable();
return 0;
```
... for what you want to do.

**Comment by srajanseth84** [comment]
<img width="575" alt="abc-crop" src="https://user-images.githubusercontent.com/46440601/156429954-47957f70-add0-4b02-a6ad-ef3287989e9c.png">
@Jake-Carter 
That's the image so what i want to do is to crop each digit and pass them separately to NN 
that's why i mentioned that loop 
for (int ...... to 8 ) for 8 separate image 
Will it work?
What would you suggest?

**Comment by srajanseth84** [comment]
@Jake-Carter 
Can i so something like first convert this image to Raw image then to uint32_t then crop it by iterating that array then copy each cropped array to memory then pass it to CNN the prediction will show for that image then iterate this process for rest of cropped array?

**Comment by Jake-Carter** [comment]
@srajanseth84 are you working with Laiwa?

**Comment by srajanseth84** [comment]
> <img alt="abc-crop" width="575" src="https://user-images.githubusercontent.com/46440601/156429954-47957f70-add0-4b02-a6ad-ef3287989e9c.png">
> 
> @Jake-Carter That's the image so what i want to do is to crop each digit and pass them separately to NN that's why i mentioned that loop for (int ...... to 8 ) for 8 separate image Will it work? What would you suggest?

@Jake-Carter Please respond to this, Can i pass input in a loop and then expect output?

**Comment by Jake-Carter** [comment]
@srajanseth84 are you working with Intellekt AI and/or Laiwa Ltd.?  We have been working with them directly to support their application and the image above is one of the images from the dataset we've been looking at.  

If you're part of the same organization we should loop you into our support chains with my colleagues.  We have been discussing alternative approaches such as regression-based models for multi-digit recognition for the past few weeks.  The algorithmic approach for individual digits would be a good starting point, but isn't ideal for the end product.

**Comment by srajanseth84** [comment]
@Jake-Carter Yeh! I'm working with Intellekt AI

**Comment by rotx-maxim** [comment]
@srajanseth84, we've moved this conversation to direct support.
