### ISSUE TITLE
CNN accelerator for other applications

### ISSUE THREAD

**Issue by benlwk** [MaximIntegratedAI/MaximAI_Documentation#58]
Dear Maxim developers,

I read in the documentation that the CNN accelerator can do "Full resolution sum-of-products arithmetic for 1024 8-bit integer channels".
- Pg. 378 in https://pdfserv.maximintegrated.com/en/an/ug7456.pdf

I am interested in using the CNN accelerator for non-AI purposes. For instance, I want to do a series of sum-of-products arithmetic, which seems to be a suitable task to utilize the CNN accelerator. However, I only see examples related to the CNN, is there any API or examples that allow us to use the CNN accelerator directly, without going through those CNN training/quantization steps? In particular, it would be great if there are some APIs that allow us to supply the inputs and obtain the sum-of-products as outputs. 

Thanks.

**Comment by rotx-maxim** [comment]
You might be able to do this by using the hooks we have for hardware verification. This is completely unsupported, not the intended use model for the device, and not very user friendly. However, if you're willing to put up with some pain, here are a few notes about how this works:

* In addition to checkpoint files, the tools can also ingest weights from numpy files (you'll find lots of them in the "test" directory). The "sample data" is a numpy file already, so the only other thing you need is a YAML file (again, see "test"). The tools will create load/unload functions for you, as well as the known answer test for making sure hardware and software agree.
* This is enabled when your YAML file specifies "test" as the architecture. The dataset is then prefixed with "weights_" to get the name of the weights numpy file, "sample_" for the sample data, etc.
* The numpy files are read in by "izer/sampleweight.py" and "izer/sampledata.py". You could of course modify this and read in something else.
* The tools will then create the configuration for this specific size of input data and weight data (the configuration is not specific to the actual data in either, but the dimensions - CHW - do matter). However, if any of the dimensions change, you will have to recreate. 
* When you manually specify weights (and optionally, biases), and you want 8-bit results, you may need to also specify "output_shift" since the reduction to 8-bit can clip to all-0 or all-1/-1.
* The "tests" directory has a few shell scripts that create examples of these numpy files (make_weights.sh, make_sample.sh, etc.).

An example build command would be:
```
#!/bin/sh
DEVICE="MAX78000"
TARGET="build-test"
python ai8xize.py --test-dir $TARGET --prefix upsample --config-file tests/test-upsample.yaml --device $DEVICE --verbose --no-version-check "$@"
```

**Comment by benlwk** [comment]
Hi Rotx,

Thanks for your promptly reply! However, it doesn't seem to be useful to me in that case. I cannot use those tools and python, I need to keep refreshing the data (i.e., the inputs and weights) and compute them on the fly. Moreover, I want to code in C rather than python.

Is there any way I can directly write onto the registers and configure the CNN accelerator to perform the computations I want? 

There could be many good use cases if your team can allow CNN accelerator to be used for other applications. For instance, one can use the CNN accelerator to perform sum-of-products used by scientific computation, image processing and even cryptography. Maybe your team could consider supporting this in the future.

Thanks!

**Comment by rotx-maxim** [comment]
The Python tools generate C code (see README for a description of the function names). As long as you keep the changes reasonable, you will be able to easily replace the weights. Replacing data is easy since that is part of the use model anyway (every inference uses different input data).
The register settings are documented in the User Guide for MAX78000 (please note that this may not be true for other devices).
