### ISSUE TITLE
MAX78000FTHR data mismatch

### ISSUE THREAD

**Issue by Weining24** [MaximIntegratedAI/MaximAI_Documentation#70]
Hi,

I am trying to train a model with my dataset.
After I implemented the model to the MAX78000. 

The _check_output()_  function reported that "Data mismatch (1/4) at address 0x50401000: Expected 0xffffeff9, read 0xffffeffe."

What is the reason for this error?
What do you think I should do to solve this problem?

Thanks.

**Comment by vicloginov** [comment]
The issue may be related to wrong **in_offset** or **out_offset** value in YAML file. It may cause data overwrite in some layer of your network. To debug which layer causes the issue you can use "**--stop-after N**" option of synthesis tool.

The option **--stop-after N** where **N** is a layer number may help to find the problematic layer by terminating the
network early without having to retrain and without having to change the weight input file. Note that this may also require 
**--max-verify-length** since intermediate outputs tend to be large, and additionally, **--no-unload** to suppress generation of the **cnn_unload()** function.
