### ISSUE TITLE
writing data from MAX78000 FTHR onto host PC

### ISSUE THREAD

**Issue by khavernathy** [MaximIntegratedAI/MaximAI_Documentation#72]
Hi, I have some working examples and models compiled onto the MAX78000 FTHR.

I was wondering if there is some example code for writing data from the card back onto the host/development PC?

Like writing a file, instead of simply `printf` for viewing data in a serial monitor. Would I have to do it all with `printf` capturing the output of the serial monitor?

I'm specifically interested in writing the camera pixel values to an image file on the development PC since I don't have the "TFT" display.

**Comment by Jake-Carter** [comment]
Hi @khavernathy, check out the [ImgCapture](https://github.com/Analog-Devices-MSDK/msdk/tree/main/Examples/MAX78000/ImgCapture) example in the MSDK.  I wrote it as an example of exactly what you describe.

There's 3 primary components to this type of thing:
1. Camera firmware to captures and buffer images, and to change camera parameters.  For larger image sizes some special tricks to buffer into the CNN data memory have been used.
2. UART firmware for serializing captured image data.  The UART firmware in the example also implements a CLI so the user can send commands.
3. A Python program running on the host PC.  It connects to the UART firmware, decodes serialized image data, and converts it to .pngs on the host PC.

**Comment by khavernathy** [comment]
Thanks!

**Comment by Jake-Carter** [comment]
Happy to help, let me know if you have any issues

**Comment by Jake-Carter** [comment]
For real image data, any of our CNN demos that use the camera would be a good reference.  See [digit-detection-demo](https://github.com/Analog-Devices-MSDK/msdk/tree/main/Examples/MAX78000/CNN/digit-detection-demo), [cats-dogs_demo](https://github.com/Analog-Devices-MSDK/msdk/tree/main/Examples/MAX78000/CNN/cats-dogs_demo), [faceid-evkit](https://github.com/Analog-Devices-MSDK/msdk/tree/main/Examples/MAX78000/CNN/faceid_evkit), etc.

Be advised that the ImgCapture example uses some tricks to repurpose the CNN accelerator as a giant block of SRAM so that larger images can be sent to the host PC.  It's not the correct way to load images or configure the CNN for inference.  See the notes [here](https://github.com/Analog-Devices-MSDK/msdk/blob/9927e9801bcf666937ca9322b02a96cdcb3e2a1f/Examples/MAX78000/ImgCapture/main.c#L235C10-L235C10).  The functions in [cnn_memutils](https://github.com/Analog-Devices-MSDK/msdk/blob/main/Examples/MAX78000/ImgCapture/include/cnn_memutils.h) will conflict with the `cnn.h`/`cnn.c` settings output by the ai8x-synthesis tool.  If you are hybridizing the two examples I suspect this is why the FIFO status update is failing - the CNN is being configured improperly at some point by the ImgCapture utility functions.

ImgCapture is really only intended for capturing and viewing images and tuning camera settings.  For loading the CNN, you will want to take only the camera code from ImgCapture - removing all of the `cnn_memutils.h` function calls.

What's the size of your input image?  I'd be happy to help get you started in the right direction.  Your image dimensions will determine whether you'll start with buffered captures, or if you'll need to implement a streaming `load_input` using the FIFOs.

**Comment by khavernathy** [comment]
thanks @Jake-Carter . I used the `cats-dogs_demo` as a template for my custom ML solution, which uses 128x128 imagery as model input. That is, 128x128x4 bytes it appears.

I'd like to safely go up to 256x256 without more complexity (without streaming with FIFO) if possible.

It looks like `digit-detection-demo` is a great example for what I'm trying to achieve. i.e. realtime, looped image classification.
